import {
  Award,
  BadgeCheck,
  Bookmark,
  BookOpen,
  Camera,
  CircleCheck,
  CircleUserRound,
  Coffee,
  Crown,
  Diamond,
  Flag,
  Flame,
  Gem,
  Gift,
  Globe2,
  Heart,
  Leaf,
  Lightbulb,
  Medal,
  Moon,
  Music,
  Palette,
  Rocket,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  Trophy,
  UserCheck,
  WandSparkles,
  Zap,
  Sun,
  type LucideIcon,
} from "lucide-react";

/** 与 LoveType 保持一致的用户标识名称徽章。 */
export const XHS_IDENTIFIER_BADGES = [
  "wand-sparkles",
  "badge-check",
  "crown",
  "star",
  "heart",
  "zap",
  "flame",
  "diamond",
  "sparkles",
  "shield-check",
  "award",
  "gem",
  "rocket",
  "trophy",
  "plus",
  "palette",
  "bookmark",
  "circle-check",
  "circle-user-round",
  "gift",
  "medal",
  "target",
  "flag",
  "leaf",
  "sun",
  "moon",
  "coffee",
  "music",
  "camera",
  "lightbulb",
  "book-open",
  "globe-2",
] as const;

export type XhsIdentifierBadge = (typeof XHS_IDENTIFIER_BADGES)[number];

/** 每组正好一行，保持选择面板的 8 列节奏。 */
export const XHS_IDENTIFIER_BADGE_GROUPS = [
  {
    id: "identity",
    badges: [
      "wand-sparkles",
      "badge-check",
      "crown",
      "shield-check",
      "circle-check",
      "circle-user-round",
      "plus",
      "award",
    ],
  },
  {
    id: "achievement",
    badges: ["star", "heart", "zap", "flame", "diamond", "sparkles", "gem", "trophy"],
  },
  {
    id: "creator",
    badges: ["medal", "target", "flag", "leaf", "rocket", "palette", "bookmark", "gift"],
  },
  {
    id: "interests",
    badges: ["sun", "moon", "coffee", "music", "camera", "lightbulb", "book-open", "globe-2"],
  },
] as const satisfies ReadonlyArray<{ id: string; badges: readonly XhsIdentifierBadge[] }>;

export const XHS_IDENTIFIER_BADGE_ICONS: Record<XhsIdentifierBadge, LucideIcon> = {
  "wand-sparkles": WandSparkles,
  "badge-check": BadgeCheck,
  crown: Crown,
  star: Star,
  heart: Heart,
  zap: Zap,
  flame: Flame,
  diamond: Diamond,
  sparkles: Sparkles,
  "shield-check": ShieldCheck,
  award: Award,
  gem: Gem,
  rocket: Rocket,
  trophy: Trophy,
  plus: UserCheck,
  palette: Palette,
  bookmark: Bookmark,
  "circle-check": CircleCheck,
  "circle-user-round": CircleUserRound,
  gift: Gift,
  medal: Medal,
  target: Target,
  flag: Flag,
  leaf: Leaf,
  sun: Sun,
  moon: Moon,
  coffee: Coffee,
  music: Music,
  camera: Camera,
  lightbulb: Lightbulb,
  "book-open": BookOpen,
  "globe-2": Globe2,
};
